# Generated by Django 2.2.13 on 2022-06-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='adults',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Взрослые'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='children',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Дети'),
        ),
    ]
