# Generated by Django 2.2.13 on 2022-06-30 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='rate',
            field=models.IntegerField(default=0, verbose_name='Baho'),
        ),
    ]
